# Base
foreground #efdfe1
background #33000e
selection_foreground #551d31
selection_background #ff668f

# Cursor
cursor #ffb1c6
cursor_text_color #551d31

# URL
url_color #eebd93

# Bordas
active_border_color #ffb1c6
inactive_border_color #191113
bell_border_color #ffb4ab

# Tab bar
active_tab_foreground #551d31
active_tab_background #ffb1c6
inactive_tab_foreground #efdfe1
inactive_tab_background #31282a
tab_bar_background #181112

# Marks
mark1_foreground #551d31
mark1_background #ffb1c6
mark2_foreground #422930
mark2_background #e3bdc6
mark3_foreground #47290b
mark3_background #eebd93

# ANSI 16 colors
color0 #191113
color8 #413739

color1 #ffb4ab
color9 #ff7f70

color2 #e3bdc6
color10 #d49ba8

color3 #eebd93
color11 #edb98c

color4 #ffb1c6
color12 #ff7a9e

color5 #c27083
color13 #d8a2af

color6 #ff336a
color14 #ff7a9e

color7 #dab4b9
color15 #f1e4e6
