# Base
foreground #efdfe1
background #33000c
selection_foreground #551d2f
selection_background #ff668b

# Cursor
cursor #ffb1c4
cursor_text_color #551d2f

# URL
url_color #edbd92

# Bordas
active_border_color #ffb1c4
inactive_border_color #191113
bell_border_color #ffb4ab

# Tab bar
active_tab_foreground #551d2f
active_tab_background #ffb1c4
inactive_tab_foreground #efdfe1
inactive_tab_background #312829
tab_bar_background #181112

# Marks
mark1_foreground #551d2f
mark1_background #ffb1c4
mark2_foreground #422930
mark2_background #e3bdc5
mark3_foreground #472a0a
mark3_background #edbd92

# ANSI 16 colors
color0 #191113
color8 #413739

color1 #ffb4ab
color9 #ff7f70

color2 #e3bdc5
color10 #d49ba7

color3 #edbd92
color11 #ecba8d

color4 #ffb1c4
color12 #ff7a9b

color5 #c27081
color13 #d8a2ad

color6 #ff3365
color14 #ff7a9b

color7 #dab4b9
color15 #f1e4e6
